### ISSUE TITLE
Request textdocument/codeAction failed

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/vscode-linter-xo#28]
> [Error - 14:41:14] Request textDocument/codeAction failed.
>   Message: Unhandled method textDocument/codeAction
>   Code: -32601 

Not sure when it happens so have to dig into it.

**Comment by unixzii** [comment]
I've just migrated one of my old project's coding style to **xo**, and it may produce 1000+ errors or warnings. Before I fix these issues, the plugin will keep logging that.

**Comment by noeladd** [comment]
I keep getting this error as well. Is there any workaround known for this? The linter won't work on this project at all.

**Comment by noeladd** [comment]
I got a stack trace with this error today. Still not sure exactly what is going on.  I've tried uninstalling and reinstalling the extension and uninstalling and reinstalling the global xo npm.  

Here's the error message I got today: 
`TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Package.isDependency (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/package.js:10:48)
    at Linter.validate (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/server.js:106:27)
    at Linter.validateSingle (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/server.js:100:21)
    at Linter.documents.onDidChangeContent.event (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/server.js:19:18)
    at CallbackList.invoke (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at /Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/node_modules/vscode-languageserver/lib/main.js:170:39
    at handleNotification (/Users/raddleman/.vscode/extensions/samverschueren.linter-xo-2.1.3/server/node_modules/vscode-jsonrpc/lib/main.js:267:17)
[Error - 10:48:39 AM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 `

**Comment by TENsaga** [comment]
Same issue here.

**Comment by nampdn** [comment]
I meet this too. It's clean install but can't get it works.

**Comment by gibbok** [comment]
same problem here

**Comment by maxbaluev** [comment]
I have same problem

**Comment by xlc** [comment]
I have fixed it here https://github.com/xlc/vscode-linter-xo/commit/d60531a3a49e428eb16d5035a6c5031760c2f118
Let me know if you want me to PR it.

**Comment by SamVerschueren** [comment]
Feel free to send the PR!
