### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#6]
```
This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:268:12)
    at StreamMessageWriter.write (/Users/wmertens/.vscode/extensions/samverschueren.linter-xo-1.2.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:22:23)
    at Object.connection.sendNotification (/Users/wmertens/.vscode/extensions/samverschueren.linter-xo-1.2.0/node_modules/vscode-jsonrpc/lib/main.js:211:27)
    at Object.result.didOpenTextDocument (/Users/wmertens/.vscode/extensions/samverschueren.linter-xo-1.2.0/node_modules/vscode-languageclient/lib/main.js:58:68)
    at LanguageClient.onDidOpenTextDoument (/Users/wmertens/.vscode/extensions/samverschueren.linter-xo-1.2.0/node_modules/vscode-languageclient/lib/main.js:384:20)
    at /Users/wmertens/.vscode/extensions/samverschueren.linter-xo-1.2.0/node_modules/vscode-languageclient/lib/main.js:299:86
    at e.invoke (/Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:14035)
    at e.fire (/Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:15488)
    at e._acceptModelAdd (/Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:18:26225)
    at t.e.handle (/Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:15:12835)
```

I can't get it to lint at all, any ideas?

**Comment by wmertens** [comment]
actually, XO doesn't work from the command line. Investigating…

**Comment by wmertens** [comment]
removed eslint and eslint-babel from my own deps, and re-installed XO, it works fine now.

I suppose the warning could be more obvious though… Perhaps add a "try running `$(npm bin)/xo` from the command line"?
