### ISSUE TITLE
After updating to 3.3.0 I'm getting ''Starting process to resolve node module xo failed" and The xo server crashed 5 times in the last 3 minutes. "

### ISSUE THREAD

**Issue by darkred** [SamVerschueren/vscode-linter-xo#99]
After updating the extension to 3.3.0 from 3.2.0 (VSCode 1.61 x64, Node 16.11.1 on win11)
whenever I try to open any folder in VSCode I'm getting these errors:

> Starting process to resolve node module xo failed
>
> The xo server crashed 5 times in the last 3 minutes. The server will not be restarted.
>
> A request has failed. See the output for more information.

That is (from bottom to top):
![2021-10-13_225842](https://user-images.githubusercontent.com/723651/137204172-0cc43f05-0bf2-4945-903e-cc467bb232a3.jpg)

<details>
<summary>The output of the 3rd/top message:</summary>

```
[Info  - 10:27:20 PM] XO Server Starting in Node v14.16.0
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 10:27:20 PM] Error: Starting process to resolve node module  xo failed
    at c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56829
    at new Promise (<anonymous>)
    at Object.Ln [as resolve] (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56531)
    at ac.resolveXO (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:6977)
    at async ac.getDocumentDiagnostics (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8838)
    at async ac.lintDocument (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8100)
[Info  - 10:27:20 PM] Connection to server got closed. Server will restart.
[Info  - 10:27:20 PM] XO Server Starting in Node v14.16.0
[Error - 10:27:21 PM] Error: Starting process to resolve node module  xo failed
    at c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56829
    at new Promise (<anonymous>)
    at Object.Ln [as resolve] (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56531)
    at ac.resolveXO (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:6977)
    at async ac.getDocumentDiagnostics (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8838)
    at async ac.lintDocument (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8100)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 10:27:21 PM] Connection to server got closed. Server will restart.
[Info  - 10:27:21 PM] XO Server Starting in Node v14.16.0
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 10:27:21 PM] Error: Starting process to resolve node module  xo failed
    at c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56829
    at new Promise (<anonymous>)
    at Object.Ln [as resolve] (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56531)
    at ac.resolveXO (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:6977)
    at async ac.getDocumentDiagnostics (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8838)
    at async ac.lintDocument (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8100)
[Info  - 10:27:21 PM] Connection to server got closed. Server will restart.
[Info  - 10:27:21 PM] XO Server Starting in Node v14.16.0
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 10:27:22 PM] Error: Starting process to resolve node module  xo failed
    at c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56829
    at new Promise (<anonymous>)
    at Object.Ln [as resolve] (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56531)
    at ac.resolveXO (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:6977)
    at async ac.getDocumentDiagnostics (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8838)
    at async ac.lintDocument (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8100)
[Info  - 10:27:22 PM] Connection to server got closed. Server will restart.
[Info  - 10:27:22 PM] XO Server Starting in Node v14.16.0
[Error - 10:27:22 PM] Error: Starting process to resolve node module  xo failed
    at c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56829
    at new Promise (<anonymous>)
    at Object.Ln [as resolve] (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:33:56531)
    at ac.resolveXO (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:6977)
    at async ac.getDocumentDiagnostics (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8838)
    at async ac.lintDocument (c:\Users\Kostas\.vscode\extensions\samverschueren.linter-xo-3.3.0\dist\server.js:46:8100)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\Microsoft VS Code\\Code.exe',
  path: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
  spawnargs: [
    '-e',
    "var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Error - 10:27:22 PM] Connection to server got closed. Server will not be restarted.

```
</details>

Thank you

**Comment by Spence-S** [comment]
Interesting @darkred - sorry for the inconvenience - just to cover my bases - do you have xo installed in the workspace? I cannot reproduce this on mac. 

And even more odd - I these errors should be caught and handled internally and not crash the server. Not sure if VSCode has some sort of mechanism there that disconnects it... 

Anyway - it looks like the error is coming from trying to resolve the path of xo in your folder:
https://github.com/microsoft/vscode-languageserver-node/blob/bc2cb78ed791e297f4f91bdb91934b251f93ff78/server/src/node/files.ts#L92

I assume you've tried restarting VSCode and everything?
